#include "ida_export.h"
#include <fstream>
#include <spdlog/spdlog.h>
#include <fmt/format.h>

namespace hype {

bool IDAExport::write(const std::filesystem::path& path, const PEImage& /*img*/, const AnalysisDB& db) {
    std::ofstream f(path);
    if (!f) { spdlog::error("cannot write: {}", path.string()); return false; }

    f << "# Generated by Hyperion\n";
    f << "import idaapi\nimport idc\nimport ida_funcs\nimport ida_name\n\n";
    f << "idaapi.auto_wait()\n\n";

    for (auto& [entry, func] : db.funcs) {
        f << fmt::format("ida_funcs.add_func(0x{:X})\n", entry);
        if (!func.name.empty() && func.name.substr(0, 4) != "sub_")
            f << fmt::format("ida_name.set_name(0x{:X}, '{}', ida_name.SN_FORCE)\n", entry, func.name);
    }

    f << "\n";
    for (auto& [addr, name] : db.names) {
        if (name.substr(0, 4) == "sub_") continue;
        f << fmt::format("ida_name.set_name(0x{:X}, '{}', ida_name.SN_FORCE)\n", addr, name);
    }

    f << "\n";
    for (auto& [addr, cmt] : db.comments) {
        std::string escaped = cmt;
        for (size_t pos = 0; (pos = escaped.find('\'', pos)) != std::string::npos; pos += 2)
            escaped.replace(pos, 1, "\\'");
        f << fmt::format("idc.set_cmt(0x{:X}, '{}', 0)\n", addr, escaped);
    }

    f << "\nprint('[Hyperion] done')\n";
    spdlog::info("exported: {}", path.string());
    return true;
}

}
